### ISSUE TITLE
How to reset state after submission?

### ISSUE THREAD

**Issue by lndgalante** [unstacked/statickit-react#8]

**Comment by derrickreimer** [comment]
Hi @lndgalante, there is not currently an API for performing state reset for the `useForm` hook. 

For more control, you can utilize the client directly to submit your form and track your state manually: https://statickit.com/docs/core

```js
import { useStaticKit } from '@statickit/react';

function MyComponent() {
  const client = useStaticKit();
  const [email, setEmail] = useState();
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    const resp = await client.submitForm("contactForm", { email });
    // ...
  }

  // ...
}
```

**Comment by lndgalante** [comment]
Thanks @derrickreimer I thought about that. Since my UI component opens and closes (conditional rendering) I've put the logic inside so I remove the hook and mount it back.
